Grp8MovieShop/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Grp8MovieShop.Models;
using Grp8MovieShop.Models.ViewModels;

namespace Grp8MovieShop.Controllers
{
    public class CustomersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Customers
        public ActionResult Index()
        {
            return View(db.Customers.ToList());
        }
        public ActionResult CheckOrders(string email)
        {
            List<OrderHistoryVM> OrdVm=new List<OrderHistoryVM>();
            if (!String.IsNullOrEmpty(email))
            {
                Customer cust = db.Customers.Where(c => c.EmailAddress.ToLower() == email.ToLower()).FirstOrDefault();
              if(cust!=null)
                {
                    OrdVm = db.Orders.Where(o => o.CustomerId == cust.Id)
                   .Join(db.OrderRows, o => o.Id, r => r.OrderId, (o, r) => new { o, r })
                   //.GroupBy(ors => ors.o.Id)
                   .Select(ord => new OrderHistoryVM
                   {
                       OrderId = ord.o.Id,
                       CustomerName = ord.o.Customer.FirstName + " " + ord.o.Customer.LastName,
                       MovieTitle = ord.r.Movie.Title,
                       OrderedDate = ord.o.OrderedDate,
                       Price = ord.r.Price,
                       TotalPrice = ord.o.TotalPrice,
                       NoofCopies = ord.r.NoofCopies

                   }).ToList();
                }
                else
                {
                    ViewBag.Message = "Please enter valid email to check orders!";
                }

                //var Tuplelist=Tuple.Create<List<Movie>,List<Order>,List<Customer>> (db.Movies.ToList(),db.Orders.ToList(), db.Customers.ToList())
              
            }
            else if(email!=null)
            {
                ViewBag.Message = "Please enter email to check orders!";
            }
            return View(OrdVm);

        }
        public ActionResult ValidateCustomer(string email)
        {
            Session["Msg"] = "Already a Customer!";
            Session["Valid"] = 1;
            Customer Cust = db.Customers.Where(c => c.EmailAddress.ToLower() == email.ToLower()).FirstOrDefault();
            if (Cust == null)
            {
                Session["Msg"] = "Not a registered Customer!";
                Session["Valid"] = 0;
            }
            else
            {
                Session["CustomerId"] = Cust.Id;
            }
            return View();
        }
        // GET: Customers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,BillingAddress,BillingZip,BillingCity,DeliveryAddress,DeliveryZip,DeliveryCity,EmailAddress,PhoneNo")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                var Cust = db.Customers.Where(c => c.EmailAddress.ToLower() == customer.EmailAddress.ToLower());
                if (Cust.Count() == 0)
                {
                    Session.Remove("EmailvalidMsg");
                    db.Customers.Add(customer);
                    db.SaveChanges();
                    Session["CustomerId"] = customer.Id;
                    ViewBag.Email = customer.EmailAddress;
                    return View("SuccessMsg");
                }
                else
                {
                    Session["EmailvalidMsg"] = "Customer already exists with email " + customer.EmailAddress;
                    return View(customer);
                }


                //return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,BillingAddress,BillingZip,BillingCity,DeliveryAddress,DeliveryZip,DeliveryCity,EmailAddress,PhoneNo")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Grp8MovieShop/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Grp8MovieShop.Models;
using Grp8MovieShop.Models.ViewModels;
namespace Grp8MovieShop.Controllers
{
    public class MoviesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Movies
        public ActionResult Index()
        {
            Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("sv-SE");
            return View(db.Movies.ToList());
        }

        // GET: Movies/Details/5
        public ActionResult Details(int? id, int isdefault)
        {
            Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("sv-SE");
            ViewBag.Isdefault = isdefault;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        public ActionResult PaginateMovies(int page = 1)
        {
            if (Session["Search"] != null) Session["PrevSearch"] = Session["Search"];
            Session.Remove("Search");
            Session["CurrentPage"] = page;
            PaginateViewModel MoviesView;
            MoviesView = new PaginateViewModel();

            MoviesView.MoviesPerLoad = 24;
            MoviesView.MoviesPerRow = 4;
            MoviesView.MoviesPerPage = 8;
            MoviesView.CurrentPage = page;
            MoviesView.Movies = CurrentPageMovies(MoviesView.CurrentPage, MoviesView.MoviesPerPage);
            MoviesView.PageCount = PaginateViewModel.NoofPages(db.Movies.Count(), MoviesView.MoviesPerPage);
            return View(MoviesView);

        }
        public IEnumerable<Movie> CurrentPageMovies(int CurrentPage, int MoviesPerPage)
        {

            int start = (CurrentPage - 1) * MoviesPerPage;
            var movies = db.Movies.OrderBy(m => m.Id);
            if (movies.Skip(start).Count() < MoviesPerPage) return movies.Skip(start);
            return movies.Skip(start).Take(MoviesPerPage);
        }

        public ActionResult MovieList()
        {
            if (Session["Search"] != null) Session["PrevSearch"] = Session["Search"];
            Session.Remove("Search");
            Session.Remove("CurrentPage");
            return View(db.Movies.ToList());

        }
        public ActionResult SearchMovie()
        {
           Session.Remove("CurrentPage");
            if (Session["PrevSearch"] != null) Session["Search"] = Session["PrevSearch"];
            return View();
        }

        public ActionResult SearchMovieList(string movie)
        {
            Session["Search"] = movie;
            var movielist = db.Movies.Where(m => m.Title.Contains(movie));
            if (String.IsNullOrEmpty(movie))
            {
                ViewBag.Flag = 1;
                ViewBag.Count = 0;
            }
            else
            {
                ViewBag.Flag = 0;
                ViewBag.Count = movielist.Count();
            }

            return View("MovieList", movielist);
        }


        public ActionResult AddtoCart(int MovieId, int IncorDec, int IsCart)
        {
            List<int> MovieIdLst = new List<int>();
            if (Session["MovieList"] != null) MovieIdLst = (List<int>)Session["MovieList"];
            if (IncorDec == 1) MovieIdLst.Add(MovieId);
            else //MovieIdLst.Remove(MovieId);
            { //to follow the sequence of selection
                MovieIdLst.Reverse();
                MovieIdLst.Remove(MovieId);
                MovieIdLst.Reverse();
            }
            //to display in particular sequence irrespective of selected sequence
            //MovieIdLst.Sort();
            Session["MovieList"] = MovieIdLst;
            Session["Count"] = MovieIdLst.Count;
            if (IsCart == 1) return RedirectToAction("DisplayCart", new { summary = 0 });
            else if (IsCart == 2) return RedirectToAction("SearchMovie");
            else if (IsCart == 3) return RedirectToAction("PaginateMovies",new { page=Session["CurrentPage"]});
            return RedirectToAction("MovieList");
        }
        public ActionResult DisplayCart(int summary)
        {
            Session["summary"] = summary;
            if (Session["MovieList"] == null)
            {
                return View("NoItems");
            }
            List<int> MovieIdLst = new List<int>();
            MovieIdLst = (List<int>)Session["MovieList"];
            List<int> DistinctMovieIdLst = new List<int>();
            DisplayCartVM VMobj = new DisplayCartVM();
            //To make the Distinct ID list from the selected movie Id's
            foreach (int id in MovieIdLst)
            {
                if (VMobj.MovieCopiesList.Count == 0)
                {
                    DistinctMovieIdLst.Add(id);
                    VMobj.MovieCopiesList.Add(MovieIdLst.Count(m => m == id));
                }
                else if (!DistinctMovieIdLst.Contains(id))
                {
                    DistinctMovieIdLst.Add(id);
                    VMobj.MovieCopiesList.Add(MovieIdLst.Count(m => m == id));
                }

            }
            //To read movie details for the selected list of movie Id's
            foreach (int id in DistinctMovieIdLst)
            {
                VMobj.DispMovieList.Add(db.Movies.Find(id));
            }
            Movie movie;
            int cnt = 0;
            //To calculate price for each selected movie based on no.of copies
            foreach (int copies in VMobj.MovieCopiesList)
            {
                movie = new Movie();
                movie = VMobj.DispMovieList.ElementAt(cnt);
                VMobj.PriceList.Add(copies * movie.Price);
                cnt += 1;
            }
            VMobj.TotalPrice = VMobj.PriceList.Sum();
            //Adding values to session to use inside SubmitOrder action
            Session["DistinctMovieIdLst"] = DistinctMovieIdLst;
            Session["PriceList"] = VMobj.PriceList;
            Session["CopiesList"] = VMobj.MovieCopiesList;
            Session["TotalPrice"] = VMobj.TotalPrice;

            return View(VMobj);
        }
        public ActionResult SubmitOrder()
        {
            Order ord = new Order();
            ord.CustomerId = (int)Session["CustomerId"];
            ord.OrderedDate = DateTime.Now;
            ord.TotalPrice = (decimal)Session["TotalPrice"];
            db.Orders.Add(ord);
            db.SaveChanges();
            var orderId = ord.Id;
            //orderId = db.Orders.Where(o => o.CustomerId == ord.CustomerId).Select(o => o.Id).FirstOrDefault();
            var ordId = db.Orders.OrderByDescending(o => o.Id).Select(o => o.Id).Take(1);
            List<int> MovieIdList = new List<int>();
            MovieIdList = (List<int>)Session["DistinctMovieIdLst"];
            List<int> CopiesList = new List<int>();
            CopiesList = (List<int>)Session["CopiesList"];
            List<decimal> PriceList = new List<decimal>();
            PriceList = (List<decimal>)Session["PriceList"];
            int idx = 0;
            foreach (int id in MovieIdList)
            {
                OrderRow ordw = new OrderRow();
                ordw.OrderId = orderId;
                ordw.MovieId = id;
                ordw.NoofCopies = CopiesList.ElementAt(idx);
                ordw.Price = PriceList.ElementAt(idx);
                //ordw.Order.TotalPrice += PriceList.ElementAt(idx);
                db.OrderRows.Add(ordw);
                db.SaveChanges();
                idx += 1; //idx=idx+1;
            }
            Session.Clear();
            Session["OrderId"] = orderId;
            return View();
        }
        // GET: Movies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Director,ReleaseYear,Price,ImageUrl")] Movie movie)
        {

            if (ModelState.IsValid)
            {
                db.Movies.Add(movie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(movie);
        }

        // GET: Movies/Edit/5
        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Director,ReleaseYear,Price,ImageUrl")] Movie movie)
        {

            if (ModelState.IsValid)
            {
                db.Entry(movie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        public ActionResult Delete(int? id)
        {
            Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("sv-SE");
            if (id == null)
            {

Grp8MovieShop/Views/Customers/CheckOrders.cshtml
@model IEnumerable<Grp8MovieShop.Models.ViewModels.OrderHistoryVM>
@{
    ViewBag.Title = "CheckOrders";
}

<h2>Order History</h2>
<form>
    <div class="col-sm-12">
        <div class="col-sm-12">
            <label>Email:</label>
            <input type="text" name="email" />

            <button>Check Orders</button>
        </div>
        @if (Model.Count() > 0)
        {
            foreach (var order in Model.Select(m => m.OrderId).Distinct())

            {
                <div class="col-sm-12 jumbotron">


                    <div class="col-sm-12"><b>Order No: </b>@order</div><hr />
                    <div class="col-sm-3">
                        <b>Movie </b>
                    </div>
                    <div class="col-sm-3">
                        <b>No.of Copies </b>
                    </div>
                    <div class="col-sm-offset-3">
                        <b>Price </b>
                    </div>
                    @foreach (var item in Model.Where(m => m.OrderId == order))
                    {

                        <div class="col-sm-3">
                            @item.MovieTitle
                        </div>
                        <div class="col-sm-3">
                            @item.NoofCopies
                        </div>
                        <div class="col-sm-offset-3">
                            @item.Price
                        </div>

                    }
                    <hr />
                    <div class="col-sm-12">
                        <b>Ordered date: </b>@Model.Where(m => m.OrderId == order).Select(m => m.OrderedDate).FirstOrDefault()
                    </div>
                    <div class="col-sm-12">
                        <b>Total Price: </b>@Model.Where(m => m.OrderId == order).Select(m => m.TotalPrice).FirstOrDefault()
                    </div>

                </div>

            }
        }
        else
        {
            <div class="col-sm-12" style="color:red">
                @ViewBag.Message
            </div>
        }
    </div>
</form>

Grp8MovieShop/Views/Customers/Create.cshtml
@model Grp8MovieShop.Models.Customer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillingAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillingAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillingAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillingZip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillingZip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillingZip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillingCity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillingCity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillingCity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveryAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveryAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryZip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveryZip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveryZip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryCity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveryCity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveryCity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, (string)Session["EmailvalidMsg"], new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Grp8MovieShop/Views/Customers/Delete.cshtml
@model Grp8MovieShop.Models.Customer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillingAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillingAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillingZip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillingZip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillingCity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillingCity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryZip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryZip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryCity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryCity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Grp8MovieShop/Views/Customers/Details.cshtml
@model Grp8MovieShop.Models.Customer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillingAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillingAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillingZip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillingZip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillingCity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillingCity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryZip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryZip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryCity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryCity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Grp8MovieShop/Views/Customers/SuccessMsg.cshtml
@{
    ViewBag.Title = "SuccessMsg";
}
<div class="container">
    <div class="jumbotron">
        <h2 style="color:green"> Successfully Registered with email id:@ViewBag.Email</h2>
        Please click on <b>Proceed</b> to continue.
        <button class="btn btn-success" onclick="location.href='@Url.Action("DisplayCart","Movies",new { summary = 1 },null)'">Proceed</button>
        <button class="btn btn-primary" onclick="location.href='@Url.Action("DisplayCart","Movies",new { summary = 0 },null)'">Back to Cart</button>
    </div>
</div>

Grp8MovieShop/Views/Customers/ValidateCustomer.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CustomerValidation</title>
</head>
<body>
    @if((int)Session["Valid"]==0)
    {
    <div>
        <h3 style="color:red">@Session["Msg"]</h3>
        Please click on <b>Register</b> to continue.
        <button class="btn btn-danger" onclick="location.href='@Url.Action("Create","Customers")'">Register</button>
    </div>
    }
    else
    {
    <div>
        <h3 style="color:green">@Session["Msg"]</h3>
        Please click on <b>Proceed</b> to continue.
        <button class="btn btn-success" onclick="location.href='@Url.Action("DisplayCart","Movies",new { summary = 1 },null)'">Proceed</button>
    </div>
    }
    
</body>
</html>